In [1]:
import pandas as pd

In [21]:
df = pd.read_csv("data/individuals_dataset.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3337 entries, 0 to 3336
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               3337 non-null   object
 1   CODGEO           3337 non-null   int64
 2   AREA_NAME        3337 non-null   object
 3   SEX              3337 non-null   object
 4   AGE              3337 non-null   int64
 5   DIPLOMA          2811 non-null   object
 6   PRO_CAT          3337 non-null   int64
 7   TYPE_HOUSE       3337 non-null   object
 8   NBPERS_HOUSE     3337 non-null   int64
 9   NB_10            3337 non-null   int64
 10  NB_11_17         3337 non-null   float64
 11  NB_18_24         3337 non-null   float64
 12  NB_25_64         3337 non-null   int64
 13  NB_65            3337 non-null   int64
 14  PMR              3337 non-null   bool
 15  DRIVING_LICENCE  3322 non-null   object
 16  NB_CAR           3337 non-null   int64
 17  TWO_WHEELER      3337 non-null   object
 18  BIKE             3337 non-null   object
 19  ELECT_SCOOTER    3337 non-null   object
 20  NAVIGO_SUB       3248 non-null   object
 21  IMAGINER_SUB     3337 non-null   bool
 22  OTHER_SUB_PT     3337 non-null   bool
 23  BIKE_SUB         3337 non-null   bool
 24  NSM_SUB          3337 non-null   bool
 25  WEIGHT_INDIV     3337 non-null   float64
 26  GPS_RECORD       3337 non-null   bool
dtypes: bool(6), float64(3), int64(8), object(10)
memory usage: 567.2+ KB

In [4]:
df.head()

,ID,CODGEO,AREA_NAME,SEX,AGE,DIPLOMA,PRO_CAT,TYPE_HOUSE,NBPERS_HOUSE,NB_10,...,TWO_WHEELER,BIKE,ELECT_SCOOTER,NAVIGO_SUB,IMAGINER_SUB,OTHER_SUB_PT,BIKE_SUB,NSM_SUB,WEIGHT_INDIV,GPS_RECORD
0,10_2978,78092,Bougival,Woman,41,NaN,4,In a couple with child(ren),2,1,...,1,2,0,False,False,False,False,False,1856.206160,True
1,10_2980,75120,Paris,Man,30,5-year-and-above higher education degree: Mast...,2,Living alone,1,0,...,0,0,0,True,False,False,False,False,1375.000372,True
2,10_2981,91326,Juvisy-sur-Orge,Man,38,5-year-and-above higher education degree: Mast...,2,In a couple without children,2,0,...,0,1,0,True,False,False,False,False,1231.812990,True
3,10_2982,91573,Saint-Pierre-du-Perray,Man,43,"3–4-year higher education degree: Licence, Pro...",2,Single parent (divorced / separated / widowed),1,1,...,0,2,0,True,False,False,False,False,426.311616,True
4,10_2984,78073,Bois-d'Arcy,Woman,39,5-year-and-above higher education degree: Mast...,2,Living alone,1,0,...,0,1,0,True,False,False,True,False,843.194726,True

In [ ]:
df['DIPLOMA'].dropna().unique()

array(["5-year-and-above higher education degree: Master's 2, DEA, DESS, Grande École Diploma, Doctorate, etc.",
       '3–4-year higher education degree: Licence, Professional Licence, Master 1, or equivalent',
       'Lower secondary certificate (Brevet) or equivalent',
       'Upper secondary diploma (Baccalauréat) or equivalent',
       'Vocational certificate (CAP, BEP) or equivalent', 'No diploma'],
      dtype=object)

In [6]:
df['TYPE_HOUSE'].dropna().unique()

array(['In a couple with child(ren)', 'Living alone',
       'In a couple without children',
       'Single parent (divorced / separated / widowed)',
       'Living with one or both parents',
       'Another family member in the household',
       'Not related to other household members',
       'In a shared apartment (flat-sharing)'], dtype=object)

In [10]:
nb_n_cols = [col for col in df.columns if col.startswith('NB_') and col != 'NBPERS_HOUSE' and col != 'NB_CAR']
check = df['NBPERS_HOUSE'] == df[nb_n_cols].sum(axis=1)
all(check)

print(df['NBPERS_HOUSE'])
print(df[nb_n_cols].sum(axis=1))

0       2
1       1
2       2
3       1
4       1
       ..
3332    1
3333    5
3334    3
3335    4
3336    1
Name: NBPERS_HOUSE, Length: 3337, dtype: int64
0       2.0
1       0.0
2       2.0
3       1.0
4       0.0
       ...
3332    1.0
3333    5.0
3334    3.0
3335    4.0
3336    1.0
Length: 3337, dtype: float64

In [11]:
cols_to_print = ['NBPERS_HOUSE'] + nb_n_cols
print(df[cols_to_print])

      NBPERS_HOUSE  NB_10  NB_11_17  NB_18_24  NB_25_64  NB_65
0                2      1       0.0       0.0         1      0
1                1      0       0.0       0.0         0      0
2                2      0       0.0       0.0         2      0
3                1      1       0.0       0.0         0      0
4                1      0       0.0       0.0         0      0
...            ...    ...       ...       ...       ...    ...
3332             1      0       0.0       0.0         0      1
3333             5      1       2.0       0.0         2      0
3334             3      0       0.0       1.0         2      0
3335             4      0       0.0       2.0         2      0
3336             1      0       0.0       1.0         0      0

[3337 rows x 6 columns]

In [18]:
df['DRIVING_LICENCE'].dropna().unique()

array([True, False], dtype=object)

In [22]:
priority_dict = {
    'No diploma': 0,
    "5-year-and-above higher education degree: Master's 2, DEA, DESS, Grande École Diploma, Doctorate, etc.": 5,
    '3–4-year higher education degree: Licence, Professional Licence, Master 1, or equivalent': 4,
    'Lower secondary certificate (Brevet) or equivalent': 1,
    'Upper secondary diploma (Baccalauréat) or equivalent': 3,
    'Vocational certificate (CAP, BEP) or equivalent': 2
}

df['DIPLOMA'] = df['DIPLOMA'].map(priority_dict)
df.drop(columns=['TYPE_HOUSE', 'AREA_NAME'], inplace=True)

df = df.applymap(lambda x: float(x) if isinstance(x, (int, float)) else (1.0 if x is True else (0.0 if x is False else x)))
df['SEX'] = df['SEX'].map({'Man': 1.0, 'Woman': 0.0})
df['DIPLOMA'] = df['DIPLOMA'].fillna(0)
df.head()

/tmp/ipykernel_12313/224170686.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: float(x) if isinstance(x, (int, float)) else (1.0 if x is True else (0.0 if x is False else x)))

,ID,CODGEO,SEX,AGE,DIPLOMA,PRO_CAT,NBPERS_HOUSE,NB_10,NB_11_17,NB_18_24,...,TWO_WHEELER,BIKE,ELECT_SCOOTER,NAVIGO_SUB,IMAGINER_SUB,OTHER_SUB_PT,BIKE_SUB,NSM_SUB,WEIGHT_INDIV,GPS_RECORD
0,10_2978,78092.0,0.0,41.0,0.0,4.0,2.0,1.0,0.0,0.0,...,1,2,0,0.0,0.0,0.0,0.0,0.0,1856.206160,1.0
1,10_2980,75120.0,1.0,30.0,5.0,2.0,1.0,0.0,0.0,0.0,...,0,0,0,1.0,0.0,0.0,0.0,0.0,1375.000372,1.0
2,10_2981,91326.0,1.0,38.0,5.0,2.0,2.0,0.0,0.0,0.0,...,0,1,0,1.0,0.0,0.0,0.0,0.0,1231.812990,1.0
3,10_2982,91573.0,1.0,43.0,4.0,2.0,1.0,1.0,0.0,0.0,...,0,2,0,1.0,0.0,0.0,0.0,0.0,426.311616,1.0
4,10_2984,78073.0,0.0,39.0,5.0,2.0,1.0,0.0,0.0,0.0,...,0,1,0,1.0,0.0,0.0,1.0,0.0,843.194726,1.0

In [23]:
df.to_csv("data/individuals_dataset_cleaned.csv", index=False)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3337 entries, 0 to 3336
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               3337 non-null   object
 1   CODGEO           3337 non-null   float64
 2   SEX              3337 non-null   float64
 3   AGE              3337 non-null   float64
 4   DIPLOMA          3337 non-null   float64
 5   PRO_CAT          3337 non-null   float64
 6   NBPERS_HOUSE     3337 non-null   float64
 7   NB_10            3337 non-null   float64
 8   NB_11_17         3337 non-null   float64
 9   NB_18_24         3337 non-null   float64
 10  NB_25_64         3337 non-null   float64
 11  NB_65            3337 non-null   float64
 12  PMR              3337 non-null   float64
 13  DRIVING_LICENCE  3322 non-null   float64
 14  NB_CAR           3337 non-null   float64
 15  TWO_WHEELER      3337 non-null   object
 16  BIKE             3337 non-null   object
 17  ELECT_SCOOTER    3337 non-null   object
 18  NAVIGO_SUB       3248 non-null   float64
 19  IMAGINER_SUB     3337 non-null   float64
 20  OTHER_SUB_PT     3337 non-null   float64
 21  BIKE_SUB         3337 non-null   float64
 22  NSM_SUB          3337 non-null   float64
 23  WEIGHT_INDIV     3337 non-null   float64
 24  GPS_RECORD       3337 non-null   float64
dtypes: float64(21), object(4)
memory usage: 651.9+ KB

In [25]:
df['BIKE'].dropna().unique()

array(['2', '0', '1', '3', '4+'], dtype=object)

In [26]:
for col in ['TWO_WHEELER', 'BIKE', 'ELECT_SCOOTER']:
    df[col] = df[col].replace('4+', '4').astype(float)
df[['TWO_WHEELER', 'BIKE', 'ELECT_SCOOTER']].dtypes

TWO_WHEELER      float64
BIKE             float64
ELECT_SCOOTER    float64
dtype: object

In [35]:
df['NAVIGO_SUB'] = df['NAVIGO_SUB'].fillna(0)
df['DRIVING_LICENCE'] = df['DRIVING_LICENCE'].fillna(0)

In [36]:
df.to_csv("data/individuals_dataset_cleaned.csv", index=False)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3337 entries, 0 to 3336
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               3337 non-null   object
 1   CODGEO           3337 non-null   float64
 2   SEX              3337 non-null   float64
 3   AGE              3337 non-null   float64
 4   DIPLOMA          3337 non-null   float64
 5   PRO_CAT          3337 non-null   float64
 6   NBPERS_HOUSE     3337 non-null   float64
 7   NB_10            3337 non-null   float64
 8   NB_11_17         3337 non-null   float64
 9   NB_18_24         3337 non-null   float64
 10  NB_25_64         3337 non-null   float64
 11  NB_65            3337 non-null   float64
 12  PMR              3337 non-null   float64
 13  DRIVING_LICENCE  3337 non-null   float64
 14  NB_CAR           3337 non-null   float64
 15  TWO_WHEELER      3337 non-null   float64
 16  BIKE             3337 non-null   float64
 17  ELECT_SCOOTER    3337 non-null   float64
 18  NAVIGO_SUB       3337 non-null   float64
 19  IMAGINER_SUB     3337 non-null   float64
 20  OTHER_SUB_PT     3337 non-null   float64
 21  BIKE_SUB         3337 non-null   float64
 22  NSM_SUB          3337 non-null   float64
 23  WEIGHT_INDIV     3337 non-null   float64
 24  GPS_RECORD       3337 non-null   float64
dtypes: float64(24), object(1)
memory usage: 651.9+ KB

In [39]:
df['CODGEO'].dropna().unique()

array([78092., 75120., 91326., 91573., 78073., 93027., 91434., 91477.,
       75113., 95680., 75107., 77445., 75115., 93033., 94079., 91587.,
       93078., 77508., 78688., 94033., 91223., 77058., 94077., 92026.,
       78420., 91667., 94054., 77337., 92040., 93051., 92046., 94046.,
       75110., 95676., 92071., 78015., 75111., 95500., 78551., 94042.,
       93013., 75118., 93048., 91377., 91272., 91549., 92035., 77122.,
       75112., 95154., 78653., 77099., 93066., 93062., 93063., 75114.,
       95019., 91103., 93061., 94080., 93005., 77389., 77040., 94002.,
       93032., 75116., 94041., 78133., 92025., 95328., 95323., 92072.,
       95176., 91665., 95218., 75117., 92060., 92048., 92062., 75101.,
       94034., 77390., 78621., 92023., 95637., 92063., 91274., 92014.,
       95489., 93071., 94022., 78089., 94028., 92032., 77143., 78646.,
       94003., 95063., 91461., 78165., 95627., 95127., 95656., 93001.,
       94038., 77463., 91136., 77053., 93070., 95028., 77243., 75119.,
       95197., 95183., 91521., 91275., 78531., 91525., 93029., 95523.,
       77237., 91174., 78642., 95058., 78686., 78624., 95078., 93050.,
       77470., 91692., 91552., 77330., 78337., 78418., 78005., 75109.,
       91421., 93055., 92024., 78123., 77320., 94076., 91286., 94017.,
       77123., 77067., 91570., 91629., 91330., 95039., 93015., 92064.,
       91216., 91228., 78401., 78586., 78383., 78126., 95660., 78517.,
       91201., 92019., 91405., 91021., 77284., 91105., 94058., 78545.,
       92033., 78382., 77111., 78172., 78231., 91553., 77352., 78372.,
       77455., 78162., 77169., 78160., 94068., 95177., 78048., 77014.,
       75108., 78442., 78220., 77513., 78358., 77379., 91589., 92050.,
       78513., 78334., 78049., 78490., 91041., 93010., 93064., 77107.,
       91468., 78674., 95612., 95252., 78431., 92004., 77217., 94081.,
       95250., 77288., 77416., 77268., 77471., 95199., 94018., 78107.,
       93053., 94071., 94067., 95370., 95392., 77468., 92012., 93047.,
       93073., 91533., 93039., 77363., 95219., 94015., 77083., 91471.,
       77164., 77285., 95277., 77100., 78640., 92002., 77251., 95060.,
       78498., 91161., 91458., 77265., 78158., 78208., 78238., 93046.,
       91600., 77216., 93077., 77479., 95241., 77199., 78242., 95582.,
       77340., 92007., 91363., 93059., 95424., 93008., 95306., 92044.,
       75105., 91016., 77409., 91376., 92077., 92036., 75103., 91386.,
       91226., 75104., 91511., 92075., 91457., 78440., 91106., 91345.,
       92049., 77370., 93007., 95313., 91687., 92051., 93031., 95527.,
       93006., 92076., 75106., 92073., 78297., 92078., 78576., 95018.,
       75102., 77131., 92020., 91122., 94074., 95203., 95480., 95371.,
       95652., 94044., 94052., 78062., 94073., 91086., 94078., 94019.,
       95607., 91338., 95428., 77511., 91207., 91027., 95563., 94065.,
       78146., 91099., 77188., 77155., 94070., 94037., 91540., 78481.,
       77001., 77315., 77294., 78311., 77449., 77373., 78455., 93072.,
       78501., 94016., 78575., 91685., 77343., 78124., 91114., 77413.,
       91315., 91425., 95051., 95210., 77487., 91659., 77464., 95056.,
       91617., 78327., 77493., 78423., 95598., 77152., 91022., 77185.,
       77400., 77132., 95504., 93057., 91098., 78638., 95298., 91347.,
       77533., 77407., 78397., 94053., 95488., 77514., 91657., 91121.,
       78396., 91200., 77255., 77072., 78335., 77150., 94059., 77271.,
       77244., 77517., 78354., 95574., 77026., 77431., 95280., 77254.,
       77192., 77333., 78361., 78557., 77108., 77495., 77175., 77258.,
       91538., 91494., 77401., 95427., 91339., 77372., 91414., 77104.,
       77025., 77296., 91645., 77474., 93074., 91547., 77276., 77316.,
       77529., 77438., 78362., 77405., 95257., 77359., 91639., 77475.,
       91671., 77171., 77039., 77482., 77266., 77368., 77326., 77055.,
       77447., 77183., 77097., 77444., 77350., 77038., 77079., 77451.,
       77477., 78192., 78224., 78537., 78321., 78465., 91661., 91691.,
       91249., 91514., 91318., 91064., 91243., 91579., 91648., 92009.,
       92022., 78650., 93049., 94043., 94011., 94004., 95491., 95268.,
       95585., 95572., 95205., 95476., 77457., 91179., 78087., 91111.,
       95142., 95353., 78255., 78643., 95351., 77215., 78486., 78502.,
       77141., 77443., 77305., 93014., 78322., 95134., 77037., 77397.,
       78499., 95566., 91649., 95509., 78609., 77500., 78125., 91312.,
       77127., 95256., 78403., 77430., 77144., 77085., 78206., 77519.,
       77419., 77222., 77311., 77168., 95052., 95352., 77433., 77394.,
       91045., 77437., 91577., 77307., 77312., 91137., 77252., 77186.,
       91235., 91534., 91432., 95535., 77182., 77516., 91333., 93045.,
       78466., 77161., 94021., 78143., 78367., 78029., 77261., 95229.,
       77382., 95658., 77005., 77118., 77414., 94060., 77077., 77068.,
       77042., 94047., 77388., 91097., 91132., 77345., 77480., 78350.,
       77423., 77004., 78497., 95170., 77384., 77335., 77130., 77249.,
       77534., 77322., 95604., 95539., 77121., 91085., 77241., 77448.,
       77178., 78189., 78190., 77377., 78681., 77462., 78522., 91038.,
       94075., 77056., 91129., 95341., 77303., 77435., 78050., 95555.,
       78003., 78118., 77069., 77348., 93079., 77177., 95120., 77211.,
       91215., 78683., 77081., 77139., 78128., 77306.])